spring:
  jpa:
    database: mysql
  datasource:
    driver-class-name: "${spring.datasource.driver-class-name}"
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true

pageable:
  size: "${page.size}"